# Generated by Django 3.2 on 2023-07-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20230729_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='tag',
            field=models.ManyToManyField(to='snippets.Tag', verbose_name='タグ'),
        ),
    ]
